version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install aws cli
          command: |
            sudo apt-get install python-dev python-pip
            sudo pip install awscli
      - run:
          name: AWS cloudfront
          command: aws configure set preview.cloudfront true

      - run:
          name: Install node modules
          command: yarn

      - deploy:
          name: Push to s3 PROD
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CI=false yarn build
              aws s3 sync dist/ s3://sound.russell.work
              aws cloudfront create-invalidation --distribution-id ERTGV5V7KXKJY  --paths "/*"
            fi
